### ISSUE TITLE
Please add feature - exception list

### ISSUE THREAD

**Issue by janusloo** [sonertari/SSLproxy#12]
Hi,

This is for a feature request: I have turned on ssl interception for my workstations and came across a minor issue: google drive refuses to connect if SSL interception is on. See the cause [here](https://support.symantec.com/en_US/article.TECH245949.html).

Is it possible to add an exception list for sites that do application side SSL authentication validation? The passthrough parameter does not work at the moment. 

With an exception list I can for example exclude sites and do not work properly and still can mitm other sites. Now I need to turn it on or off. It is a one for all or none for all at this time. 

Thank you so much for your effort and time in this excellent software!

**Comment by sonertari** [comment]
Hi @janusloo, yes, this is an issue we have discussed [here](https://github.com/sonertari/UTMFW/issues/4). (As we have discussed there, the passthrough option cannot solve this issue.) I think you are right, we need a solution for this.

Exception/bypass/passthrough lists may really be the correct solution, as you say. But have you come across other solutions? Please post relevant links you think may help. I am planning to work on a possible solution asap.

**Comment by janusloo** [comment]
Hi @sonertari no I did not have any success in finding other solutions to this issue. That's why I suggested to add exclusion list as a solution... unless you know another way to bypass this technical challenge?

If I found something I will definitely post it here. Thank you for looking at it.

**Comment by sonertari** [comment]
Hi @janusloo, can you try the develop branch and report back? It seems to work here.

**Comment by janusloo** [comment]
Hi @sonertari thanks for the quick fix.... I will test it when I am home and report back

**Comment by janusloo** [comment]
Hi @sonertari, i installed the develop branch but did not find any new parameters or the passthrough still doesn't work otherwise. I maybe missing something??

Thanks!

**Comment by sonertari** [comment]
I guess you are on master not develop (you can either fork the repo and switch to develop branch, or go to main project page, select develop on the branch dropdown box, and Download the SSLproxy-develop.zip file). There are a couple of sample (commented out) PassSite lines at the end of sslproxy.conf file. You cannot miss it. I have updated the documentation too.

**Comment by janusloo** [comment]
Hi thanks.I have compiled and installed it. To test, I put in the following parameter in the configuration file, sslproxy.conf:

PassSite https://accounts.google.com/o/oauth2/token*

This is the Google Sync plugin I use in KeePass and it is the URL that the plugin would error out when I turned on the SSL inspection. How to use the PassSite? Do I put in the URL here or the domain name(s) of the certificate it forges? It still errors out that the web request to the URL has failed. I have PassThrough option enabled though.

**Comment by sonertari** [comment]
You should use SNI or Common Names as PassSite paramater (not URLs). In your case for this URL, I have looked into the certificate of that site and seen that the common name is `accounts.google.com`. So, if this is correct, you should use the following line: `PassSite accounts.google.com` (do not use *).

So, you need to find the SNI and Common Names of the sites you want to pass through. If you enable the detailed debug logs of SSLproxy and start it with `-D4` option, SSLproxy will tell you all such details.

Btw, I cannot reproduce the crash with that URL line in your post. That option is wrong, but it shouldn't crash SSLproxy either. Or could it be something else?

**Comment by janusloo** [comment]
Okay I followed your instructions and put accounts.google.com in PassSite but it now generated this error: 
Error: TrustFailure (The authentication or decryption has failed.). And sslproxy got killed by signal 11. I don't really know what happened.

**Comment by sonertari** [comment]
This does not seem related to Passthrough or PassSite options, but related to OpenSSL. And I guess this was the same signal 11 crash you mentioned before. When I google for that error, I read that it may be related with missing trusted cert authorities. Have you installed the system from scratch (or are you using the same system as before), or somehow are you missing a trust store? If the same error happens when you disable Passthrough/PassSite options, then the issue must be really about trust store.

**Comment by sonertari** [comment]
`-D4` option would be really helpful to investigate such issues. You can send such detailed logs to my e-mail address, if you want.

**Comment by janusloo** [comment]
> This does not seem related to Passthrough or PassSite options, but related to OpenSSL. And I guess this was the same signal 11 crash you mentioned before. When I google for that error, I read that it may be related with missing trusted cert authorities. Have you installed the system from scratch (or are you using the same system as before), or somehow are you missing a trust store? If the same error happens when you disable Passthrough/PassSite options, then the issue must be really about trust store.

@sonertari hi you are right about missing the self-signed in the system's trust store. I added it and now the google sync authentication goes through without a hitch. The signal 11 error still occurs though.

Please see below the startup message:
```
SSLproxy  (built 2019-04-21)
------------------------------------------------------------------------------
WARNING: Something is wrong with the version compiled into sslproxy!
The version should contain a release number and/or a git commit reference.
If using a package, please report a bug to the distro package maintainer.
------------------------------------------------------------------------------
Build info: V:DIR N:
Features: -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.1.0j  20 Nov 2018 (101000af)
rtlinked against OpenSSL 1.1.0j  20 Nov 2018 (101000af)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: tls10 tls11 tls12 
SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
compiled against libnet 1.1.6
rtlinked against libnet 1.1.6
compiled against libpcap n/a
rtlinked against libpcap 1.8.1
4 CPU cores detected
Generated RSA key for leaf certs.
SSL/TLS protocol: negotiate

```
I currently have the following openssl version installed:
`openssl/stable,now 1.1.0j-1~deb9u1 armhf [installed]`

Please advise. Thank you.

**Comment by janusloo** [comment]
> `-D4` option would be really helpful to investigate such issues. You can send such detailed logs to my e-mail address, if you want.

Yes I have debug level 4 turned on, it is the default. Before signal 11 there were only information about successfully forged certificate. No other error messages.

**Comment by sonertari** [comment]
For very detailed debug logs, you also need to compile with DEBUG_PROXY macro enabled (in GNUmakefile, and enable DEBUG_OPTS too), and then start sslproxy with -D4. Can you somehow send me those detailed debug logs?

I think that `google sync authentication go[ing] through` and `self-signed in the system's trust store` are not related. I don't know which system you mean, but you don't need to add CA cert you use with the sslproxy -c option to your system's thrust store (you should add it to the client systems or programs). Instead, I think you have fixed your PassSite configuration, and that is why google can pass through now. (So I still think that if you *disable* Passthrough and PassSite, you will still get the same signal 11 crash, can you try that? In other words, I still think there is a problem with the thrust store, which is not related with Passthrough/PassSite options.)

**Comment by janusloo** [comment]
Okay @sonertari I have recompiled and reinstalled sslproxy as per your instructions. I have copied the log out... can I paste them here?

And I also tried with disabled passthrough and passsite parameters... it runs smoothly without signal 11.

**Comment by sonertari** [comment]
Can you compress it and send to my gmail address?

**Comment by janusloo** [comment]
What's your gmail address? I can't seem to find it here on your profile page.

**Comment by sonertari** [comment]
`sslproxy -V`

**Comment by janusloo** [comment]
Okay here it is:

```
SSLproxy  (built 2019-04-24)
------------------------------------------------------------------------------
WARNING: Something is wrong with the version compiled into sslproxy!
The version should contain a release number and/or a git commit reference.
If using a package, please report a bug to the distro package maintainer.
------------------------------------------------------------------------------
Copyright (c) 2017-2019, Soner Tari <sonertari@gmail.com>
https://github.com/sonertari/SSLproxy
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:DIR N:
Features: -DDEBUG_OPTS -DDEBUG_PROXY -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.1.0j  20 Nov 2018 (101000af)
rtlinked against OpenSSL 1.1.0j  20 Nov 2018 (101000af)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: tls10 tls11 tls12 
SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
compiled against libnet 1.1.6
rtlinked against libnet 1.1.6
compiled against libpcap n/a
rtlinked against libpcap 1.8.1
4 CPU cores detected

```

**Comment by sonertari** [comment]
No, my e-mail address is there, see the output you've posted :).

**Comment by janusloo** [comment]
Okay pls check your mail for the output file

**Comment by janusloo** [comment]
I have recompiled everything and with new openssl version 1.1.1b but got the following error:
`Error from bufferevent: 0:- 337047686:134:certificate verify failed:20:SSL routines:367:tls_process_server_certificate.
`

Here is the output of sslproxy -V:
```
SSLproxy  (built 2019-04-30)
------------------------------------------------------------------------------
WARNING: Something is wrong with the version compiled into sslproxy!
The version should contain a release number and/or a git commit reference.
If using a package, please report a bug to the distro package maintainer.
------------------------------------------------------------------------------
Copyright (c) 2017-2019, Soner Tari <sonertari@gmail.com>
https://github.com/sonertari/SSLproxy
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:DIR N:6b59204
Features: -DDEBUG_OPTS -DDEBUG_PROXY -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
Local process info support: no
compiled against OpenSSL 1.1.1b  26 Feb 2019 (1010102f)
rtlinked against OpenSSL 1.1.1b  26 Feb 2019 (1010102f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: tls10 tls11 tls12
SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
compiled against libnet 1.1.6
rtlinked against libnet 1.1.6
compiled against libpcap n/a
rtlinked against libpcap 1.8.1
4 CPU cores detected
```

I keep getting the above error when I have imported the self-signed certificate to the trust store on the client system. The crashes are gone now but sslproxy doesn't create forged certificates anymore. I can't seem to find a solution on google. Do you know what can be the cause here? Thanks!

**Comment by sonertari** [comment]
You should set `VerifyPeer` to `no` in you config. Btw, you still have not sent me debug logs (as I explained in my reply to your e-mail, the logs you have sent there are not debug logs, but I guess you have fixed that problem somehow now).

**Comment by janusloo** [comment]
The errors are gone now, certificates can be forged. The crash remains. I will send you the log as per your instructions in a mail.

**Comment by sonertari** [comment]
Thanks @janusloo for the debug logs. The crash you reported was my mistake: SNI can be null, but I wasn't check that case. I think I have fixed it on the develop branch now. Can you try the develop branch and report back please?

**Comment by janusloo** [comment]
@sonertari thanks for the fix. I have recompiled everything and am testing it now. So far there has been no crash and it is stable. The passthrough works very well too! Will report back if I encounter any new issues.

**Comment by sonertari** [comment]
Great, thanks.

**Comment by janusloo** [comment]
Hi @sonertari, is it technically feasible to automate the passthrough of certain certificates that cannot be forged (due to certificate pinning inside client app)? Now I have to inspect the debug log to find out what SNI the site I am visiting uses so to exclude them in PassSite. It can be daunting to find what I look for. It would be super user friendlier if the passthrough can be done/guessed automatically. 

Just a suggestion...

**Comment by sonertari** [comment]
Yeah, full automatic passthrough sounds like a nice idea at first. But, don't forget that SSLproxy is developed for deep SSL inspection. I use it in my UTMFW project for network security: to decrypt and inspect SSL traffic for viruses, spam, malicious web content, and intrusions. Imagine an attacker, such as a malicious site or an internal client, who somehow intentionally triggers an SSL error in SSLproxy and causes it to switch to (full automatic) passthrough mode. Does it still sound like a good idea?

Passthrough mode goes against the very purpose of SSLproxy: Deep SSL inspection for network security. That is why I disable it in UTMFW. (Hmm, I guess I should separate the Passthrough option from the PassSite feature, i.e. the PassSite feature should not require the Passthrough mode, otherwise the PassSite feature will potentially pose a more important security risk than it does by itself only.)

If a system admin chooses to enable the Passthrough mode and use the PassSite option, s/he should be very careful and write the most specific PassSite rule. In fact, s/he should use the per site user/keyword filtering feature of the PassSite option as much as possible, see the documentation for this feature. For example, Google Drive can be passed through for certain users and for their Android smartphones only, not for all users and all device types. It is possible to write such PassSite rules using the user/keyword filters, e.g. `PassSite googledrive.com soner android`, and the user `soner` should log in to UTMFW on his Android smartphone with a description text containing the word `android` in it (all this is available in UTMFW 6.5, which I will release soon).

Btw, you don't have to use the debug logs (that was just a suggestion), instead you can capture the certificate somehow (e.g. using wireshark/tcpdump or firefox site info) and look into it for SNI and/or Common Names fields.

**Comment by janusloo** [comment]
I understand your point of view about sslproxy's purpose. However, the passthrough feature is much needed to bypass SSL inspection for sites that deploy server-side certificate authentication. In my opinion, there is no exception to passthrough: it's a yes or no. I wonder if adding filters will be helpful since the site is unreachable in the first place (hence passthrough). I won't be running UTMFW, so I will not be able to test its usefulness.

So far sslproxy is running without any (new) issues. I think this thread can be closed. I will log a bug report here if any issues arise in the future. Thank you so much! You have been very helpful and fast in fixing the issues.

**Comment by sonertari** [comment]
Thank you for your help too. Btw, with my last commit PassSite does not require Passthrough anymore, check it out if you are interested. Closing this issue now.

**Comment by janusloo** [comment]
Thanks @sonertari , is it the official version or still develop?

**Comment by sonertari** [comment]
Still the develop branch.

**Comment by janusloo** [comment]
Hi @sonertari how do I use the sepecific user/keyword filters for the PassSite with sslproxy? If I understand you correctly, it is in UTMFW (the bundle)? If so I am interested in running UTMFW in a VMWare VM.

**Comment by sonertari** [comment]
The sslproxy(5) man page explains the user/keyword filters for the PassSite option. The sample sslproxy.conf file has PassSite examples. What is the specific PassSite rule you want to write?

Yes, it is a good idea to try UTMFW in a VM. Its installation script configures a network user `utmfw`, which you can write PassSite rules for (you can of course easily add other network users on the WUI of UTMFW too).

**Comment by janusloo** [comment]
I just wanna filter out some rules for some devices, like android and laptop. Just don't know how it works if I only use sslproxy and not the whole suite.

**Comment by sonertari** [comment]
This cannot be answered in a reply here. So, I suggest that you read all documentation (especially the user auth section of the SSLproxy README), understand what all these are trying to achieve, and try and experiment with user auth in UTMFW, available out of the box. The key question you should be able to answer may be: What is user description? Then I think you can understand and use user/keyword filtering.
