### ISSUE TITLE
Simple HTTPS request issue (OpenWRT)

### ISSUE THREAD

**Issue by alfreema** [sonertari/SSLproxy#19]
I can't seem to get SSLProxy to successfully make an outbound HTTPS connection.

Running on:

> root@OpenWrt:~# uname -a
> Linux OpenWrt 4.14.63 #0 Thu Aug 16 07:51:15 2018 mips GNU/Linux

When I issue this command:

> root@OpenWrt:~# /tmp/sslproxy -c /etc/sslproxy/ca.crt -k /etc/sslproxy/ca.key -D https 192.168.8.1 8443 up:8000 ua:192.168.8.176 ra:192.168.8.1

I get the following output:

> SSLproxy v0.7.0-2-gcb67c33-dirty (built 2020-02-14)
> Copyright (c) 2017-2019, Soner Tari <sonertari@gmail.com>
> https://github.com/sonertari/SSLproxy
> Copyright (c) 2009-2019, Daniel Roethlisberger <daniel@roe.ch>
> https://www.roe.ch/SSLsplit
> Build info: V:GIT
> Features: -DHAVE_NETFILTER
> NAT engines: netfilter* tproxy
> netfilter: IP_TRANSPARENT IP6T_SO_ORIGINAL_DST
> Local process info support: no
> compiled against OpenSSL 1.0.2u  20 Dec 2019 (1000215f)
> rtlinked against OpenSSL 1.0.2u  20 Dec 2019 (1000215f)
> OpenSSL has support for TLS extensions
> TLS Server Name Indication (SNI) supported
> OpenSSL is thread-safe with THREADID
> OpenSSL has engine support
> Using SSL_MODE_RELEASE_BUFFERS
> SSL/TLS protocol availability: tls10 tls11 tls12
> SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
> OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
> compiled against libevent 2.0.22-stable
> rtlinked against libevent 2.0.22-stable
> compiled against libnet 1.2-rc3
> rtlinked against libnet 1.2-rc3
> compiled against libpcap n/a
> rtlinked against libpcap 1.8.1
> compiled against sqlite 3.31.1
> rtlinked against sqlite 3.23.1
> 1 CPU cores detected
> Generated RSA key for leaf certs.
> Global SSL/TLS protocol: negotiate
> proxyspecs:
> - listen=[192.168.8.1]:8443 ssl|http netfilter
> parent dst addr= [192.168.8.176]:8000
> child src addr= [192.168.8.1]:0
> opts=|ALL:-aNULL|no ecdhcurve|no crlurl|remove_http_referer|verify_peer|no user_auth_url|300|8192
> SSL/TLS protocol: negotiate
> Loaded CA: '[removed]'
> Loaded ProxySpec CA: '[removed]'
> Privsep fastpath disabled
> Created self-pipe [r=3,w=4]
> Created chld-pipe [r=5,w=6]
> Created socketpair 0 [p=7,c=8]
> Created socketpair 1 [p=9,c=10]
> Created socketpair 2 [p=11,c=12]
> Created socketpair 3 [p=13,c=14]
> Created socketpair 4 [p=15,c=16]
> Created socketpair 5 [p=17,c=18]
> Privsep parent pid 4403
> Privsep child pid 4404
> Using libevent backend 'epoll'
> Event base supports: edge yes, O(1) yes, anyfd no
> Received privsep req type 03 sz 5 on srvsock 7
> proxy_listener_setup: listen=[192.168.8.1]:8443 ssl|http netfilter
> parent dst addr= [192.168.8.176]:8000
> child src addr= [192.168.8.1]:0
> opts=|ALL:-aNULL|no ecdhcurve|no crlurl|remove_http_referer|verify_peer|no user_auth_url|300|8192
> SSL/TLS protocol: negotiate
> Dropped privs to user nobody group - chroot -
> Received privsep req type 00 sz 1 on srvsock 9
> Received privsep req type 00 sz 1 on srvsock 11
> Received privsep req type 00 sz 1 on srvsock 13
> Received privsep req type 00 sz 1 on srvsock 15
> Received privsep req type 00 sz 1 on srvsock 17
> Inserted events:
>   0x77f6fd78 [fd 6] Read Persist
>   0x74cecc [fd 7] Read Persist
>   0x77f6fc68 [fd 5] Read Persist
>   0x74caf0 [fd 15] Signal Persist
>   0x74f130 [fd 3] Signal Persist
>   0x74f230 [fd 1] Signal Persist
>   0x74f330 [fd 2] Signal Persist
>   0x74f8d0 [fd 13] Signal Persist
>   0x74f9c0 [fd 16] Signal Persist
> Initialized 2 connection handling threads
> Started 2 connection handling threads
> Starting main event loop.

And then when I test it by issuing a curl statement that hands off to sslproxy, sslproxy returns the following:

> SNI peek: [www.fireshark.com] [complete], fd=17
> Connecting to [13.249.79.115]:443
> Client-side BEV_EVENT_ERROR
> Error from bufferevent: 0:- 336134278:134:(null):20:(null):144:(null)
> SSL_free() in state 00003005 = SSL_ST_CONNECT|SSL_ST_ACCEPT|0005 = SSLERR (error) [connect socket]

I'm not sure what this is telling me.  Any ideas on things to try to get this working?

**Comment by sonertari** [comment]
You can obtain very verbose debug logs if you compile sslproxy with the DEBUG_PROXY macro in GNUmakefile, and start it with the -D4 option.

But looking at the last logs you provide, it seems like the problem is on the client side. In fact, sslproxy successfully connects to the server (www.fireshark.com) and completes SNI peek. So are you sure your listening program is running and running correctly?

**Comment by alfreema** [comment]
Ahhhh, no I am not sure it's behaving properly (well it does work with HTTP, but that's fools gold).  From the output I thought it was on the initial connection to the target destination side (sslproxy is the client to the initial target request).  Now that I know it's on the other side, I will work through that!

**Comment by sonertari** [comment]
If plain HTTP is working fine, I think secure HTTP should work fine too, without any modification to your listening program. Actually, the listening programs are not aware of this difference (that the actual connection was secure or not), unless they process the specific field (s or p) for it in SSLproxy line in the first packet.

Btw, the options you pass to sslproxy means that you are trying to achieve a configuration with a remote listening program (you use ua and ra options). So if your listening program was running fine locally, but not remotely, then the culprit may not be the listening program.

Note that you can find a sample listening program under the folder `extra/lp` in the sources, if you like.

**Comment by alfreema** [comment]
Bah, after diving in more there was a comedy of errors in the network setup (issues with iptables and Windows 10 firewall blocking WSL Ubuntu process).   Sorry for the trouble (though your response sent me looking in the right direction)!

**Comment by rakeshbansod** [comment]
Hi @alfreema ,
I am also trying SSLProxy on openwrt.
Somehow, my sslproxy is not intercepting traffic my client connected to my router.
If I add a rule in PREROUTING to redirect the traffic to it, HTTP/HTTPS traffic stops work as it is trying to go to sslproxy port.
but i am unable to see any logs in sslproxy. I have compiled SSLProxy with -DDEBUG_PROXY.
Is there anything that I am missing?
Can you help me out here?

I am using lp from testproxy as the listening program.
Using this proxyspec
ProxySpec {
	Proto https

	Addr 127.0.0.1
	Port 8444

	DivertAddr 127.0.0.1
	DivertPort 8080

	ReturnAddr 127.0.0.1

	NatEngine netfilter
	#SNIPort 443
	#TargetAddr 127.0.0.1
	#TargetPort 9443

}

**Comment by alfreema** [comment]
Rakesh,

It has been too long since I worked on this, and have touched tens of thousands of lines of code in other research.

My memory has faded at this point, sorry.

-a
