### ISSUE TITLE
Packet Tampering

### ISSUE THREAD

**Issue by Alphadan28** [sonertari/SSLproxy#20]
i need to tamper packets, (replace a string), tried to use netsed but there is no option to specify the return port and that's required for netsed, would you recommend any option to achieve my goal?...

i have no clue how to solve this because i read in the man, that the return port is dinamically asigned and sent in the 1st packet to the proxy listener... would you en-light me pls.

**Comment by sonertari** [comment]
You need to write your own listening program to support the mode of operation required by sslproxy. All listening programs, i.e. netsed in your case, should be modified for this purpose.

You can find a sample listening program under `extra/lp`. Basically, you need to parse the sslproxy line inserted into the first packet of each connection, and return the packets to the dynamically assigned address on that line. The README explains this in detail.

**Comment by Alphadan28** [comment]
Thanks for your time, I was thinking about doing exactly that, but taking a shortcut Im planning to  modify the netsed to read the the dinamicaly asigned port and use it instead of the fixed provided by the cmd line.

**Comment by Alphadan28** [comment]
Btw may be I'm misunderstanding the inner workings of the sslproxy does the  data coming through the listening proxy comes plain or with encrypted? excuse my ignorance.

**Comment by Alphadan28** [comment]
just checked the code of your lp it works just fine, it would serve my purpose but i need to modify it, would you give some tips where to implement a string replace avoiding the packed fragmentation?

**Comment by sonertari** [comment]
To modify the packets from client to server, you should use `prototcp_bev_readcb_src`. In the other direction, use `prototcp_bev_readcb_dst`.

**Comment by Alphadan28** [comment]
wow thanks for your help gonna try to do it.

**Comment by Alphadan28** [comment]
Finally made it work, thanks again for your help.

**Comment by PinchenCui** [comment]
> Finally made it work, thanks again for your help.

Hello,

I'm trying to do a similar string replace task, would you mind to give me some clues? I cannot find the extra/lp in the source.
