### ISSUE TITLE
Troubles with netfilter TPROXY

### ISSUE THREAD

**Issue by kalashny** [sonertari/SSLproxy#24]
Hi! After configuring iptables rule with TPROXY sslproxy has stopped accepting connections. And at the same time, REDIRECT rule works perfectly, and new connections appeared in output with -D option. Installation was performed on CentOS 6.5.
Engine was detected correctly: netfiler* tproxy
![v](https://user-images.githubusercontent.com/56436495/95474686-165afd80-098e-11eb-9481-9ac60b2b4c80.PNG)

An attempt in the directive HAVE_NETFILTER to use methods from directive IP_TRANSPARENT was successful, then rule with TPROXY works fine. It is strange that packets were processed by HAVE_NETFILTER (nat_netfilter_lookup_cb), although they should be processed IP_TRANSPARENT (nat_getsockname_lookup_cb, nat_iptransparent_socket_cb). Or have I made a mistake somewhere?

**Comment by sonertari** [comment]
Can you also provide the command line or configuration options you run sslproxy with?

**Comment by kalashny** [comment]
Sorry, it was my mistake. netfilter used as engine by default, just had to look output sslproxy -E. Star in output sslproxy -E 
probably also talks about it.
With option -e tproxy rule with TPROXY works fine.
![engine](https://user-images.githubusercontent.com/56436495/95498038-ecb0cf00-09ab-11eb-94c1-2b03de681bde.PNG)

**Comment by KuYiDong** [comment]
Could you please share with me how you configured the Tproxy setup?
