### ISSUE TITLE
Issue guidelines wrt to networkengineering.stackexchange.com

### ISSUE THREAD

**Issue by sayrer** [sonertari/SSLproxy#29]
I asked a question about this on [Network Engineering](https://networkengineering.stackexchange.com/), having read the guidelines here. They closed it, saying "Unfortunately, questions about hosts/servers and protocols above OSI layer-4 are off-topic here, as are product or resource recommendations. You could try to ask this question on Super User."

Confusing, since the [wikipedia article](https://en.wikipedia.org/wiki/OSI_model#Layer_4:_Transport_Layer) says "Transport Layer Security (TLS) does not strictly fit inside the model either. It contains characteristics of the transport and presentation layers.".

**Comment by sayrer** [comment]
Example: https://networkengineering.stackexchange.com/questions/74482/how-can-i-use-sslproxy-to-downgrade-all-connections-to-ssl3-for-an-old-macintosh

**Comment by sonertari** [comment]
The [Issue Guidelines](https://github.com/sonertari/SSLproxy/blob/master/.github/ISSUE_TEMPLATE.md) of SSLproxy lists both [Network Engineering](https://networkengineering.stackexchange.com/) and [Super User](https://superuser.com/). You should choose **the most applicable Stack Exchange site**, as the guideline clearly reads, for the issue you want to report.

Btw, you may want to use [SSLsplit](https://github.com/droe/sslsplit), not SSLproxy for [the question you ask on Network Engineering](https://networkengineering.stackexchange.com/questions/74482/how-can-i-use-sslproxy-to-downgrade-all-connections-to-ssl3-for-an-old-macintosh). But note that protocol configuration in sslsplit is global,  so it enables both clients and servers to connect to sslsplit in SSL3, if OpenSSL or LibreSSL version compiled and rtlinked with sslsplit supports SSL3 (HAVE_SSLV3). In other words, there is no configuration applied only to client or server side.

**Comment by sayrer** [comment]
Yeah, I caught that and guessed wrong. They just made it sound like SSLproxy questions would never be applicable.
