### ISSUE TITLE
Global PassSite and modern passsite_filter

### ISSUE THREAD

**Issue by maxalex301** [sonertari/SSLproxy#33]
Hi, thanks for excelent project )

In latest release I try specify global PassSite filter, but it ignored (
After review code, I found passsite_filter creates only from global->spec, but not from global->opts.
Is it bug?

**Comment by sonertari** [comment]
The order of options and rules defined in the conf file is important. I guess that in your conf file the global PassSite rules are below the proxyspec lines. Please move the PassSite rules you want cloned to certain proxyspecs above those proxyspecs. (The sample PassSite rules on the UTMFW project are at the bottom of its sslproxy.conf file, I guess that's misleading users, sorry.)

Btw, if you need to use something like PassSite rules, then I recommend the new filtering rules on the develop branch. I think they are stable enough now, although I am still developing them heavily. Please see [the filtering rules section](https://github.com/sonertari/SSLproxy/tree/develop#filtering-rules) in the README on the develop branch. The PassSite option will be deprecated in favor of filtering rules in the future. And the filtering rules are more flexible and powerful.

**Comment by maxalex301** [comment]
Thanks for quick answer. New filters is very useful.
