### ISSUE TITLE
make warning on Linux

### ISSUE THREAD

**Issue by janusloo** [sonertari/SSLproxy#4]
Please supply the following with bug reports to allow for diagnostics:

-   Output of `sslsplit -V`
-   Output of `uname -a`
-   Exact command line arguments used to run `sslsplit`
-   Relevant part of debug mode (-D) output, if applicable
-   NAT redirection rules you are using, if applicable
-   List of failing unit tests in `make test` output
-   Other relevant data such as PCAPs, logs, screenshots etc

For build problems, please supply:

-   Output of `uname -a`
Linux DietPi 4.14.22-v7+ #1096 SMP Mon Feb 26 19:14:22 GMT 2018 armv7l GNU/Linux
-   Full output of failed `make` including the header
Not failed make but warnings:
Via pkg-config: openssl libevent libevent_openssl libevent_pthreads check
Build options:  -DHAVE_NETFILTER
uname -a:       Linux DietPi 4.14.22-v7+ #1096 SMP Mon Feb 26 19:14:22 GMT 2018 armv7l GNU/Linux

pxythrmgr.c:94:50: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 4 has type ‘long int’ [-Wformat=]
     if (asprintf(&msg, "EXPIRED: thr=%d, time=%lld%s%s\n",
                                                  ^
pxythrmgr.c: In function ‘pxy_thrmgr_print_thr_info’:
pxythrmgr.c:203:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if (atime >= tctx->thrmgr->opts->expired_conn_check_period) {
              ^~
pxythrmgr.c:204:66: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 7 has type ‘time_t {aka long int}’ [-Wformat=]
     if (asprintf(&smsg, "IDLE: thr=%d, id=%u, ce=%d cc=%d, at=%lld ct=%lld%s%s\n",
                                                                  ^
pxythrmgr.c:204:74: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 8 has type ‘time_t {aka long int}’ [-Wformat=]
     if (asprintf(&smsg, "IDLE: thr=%d, id=%u, ce=%d cc=%d, at=%lld ct=%lld%s%s\n",
                                                                          ^
pxythrmgr.c:238:44: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 4 has type ‘size_t {aka unsigned int}’ [-Wformat=]
  if (asprintf(&smsg, "STATS: thr=%d, mld=%lu, mfd=%d, mat=%lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                            ^
pxythrmgr.c:238:62: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 6 has type ‘time_t {aka long int}’ [-Wformat=]
  if (asprintf(&smsg, "STATS: thr=%d, mld=%lu, mfd=%d, mat=%lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                                              ^
pxythrmgr.c:238:72: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 7 has type ‘time_t {aka long int}’ [-Wformat=]
  if (asprintf(&smsg, "STATS: thr=%d, mld=%lu, mfd=%d, mat=%lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                                                        ^
pxythrmgr.c:238:121: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 12 has type ‘size_t {aka unsigned int}’ [-Wformat=]
 =%d, mld=%lu, mfd=%d, mat=%lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                                                                         ^
pxythrmgr.c:238:130: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 13 has type ‘size_t {aka unsigned int}’ [-Wformat=]
 %lu, mfd=%d, mat=%lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                                                                         ^
pxythrmgr.c:238:138: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 14 has type ‘size_t {aka unsigned int}’ [-Wformat=]
 =%d, mat=%lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                                                                         ^
pxythrmgr.c:238:147: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 15 has type ‘size_t {aka unsigned int}’ [-Wformat=]
 %lld, mct=%lld, iib=%llu, iob=%llu, eib=%llu, eob=%llu, swm=%lu, uwm=%lu, to=%lu, err=%lu, si=%u\n",
                                                                                         ^
-   Version and origin of OpenSSL used
1.1.0f-3+deb9u1
-   Version and origin of libevent used
https://github.com/libevent/libevent

I don't recall having these warnings while on Dietpi Jessie. Maybe some configuration issue? The make was successful however but I am not sure if it is stable. Thank you for your time.

**Comment by sonertari** [comment]
Thanks @janusloo for the report. Those warnings are due to time_t being 64 bits on OpenBSD but 32 bits on Linux. I've applied the suggested fix mentioned here https://www.openbsd.org/papers/eurobsdcon_2013_time_t/mgp00029.html. So the commit https://github.com/sonertari/SSLproxy/commit/f6a63c33b13ba39bb9d9aa40d25e8e462062298f should fix the issue, but no need to hurry, because %lld >= time_t. Please report back so I can close the issue.

**Comment by sonertari** [comment]
And I don't get the other warnings, but my last [commit](https://github.com/sonertari/SSLproxy/commit/0fee063e0c13d47e271ecdabb6be024666639104) should fix them for you. I should have used %zu for size_t anyway.

**Comment by janusloo** [comment]
Thanks @sonertari I just updated to the last commit and the warnings have reduced to only one:
pxythrmgr.c:61:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    if (elapsed_time > tctx->thrmgr->opts->conn_idle_timeout) {
                     ^
Maybe not a big deal but I thought I should let you know. Thank you for your support.

**Comment by sonertari** [comment]
I don't see comparison warnings on 64-bit OpenBSD or Linux, even with -Wsign-compare, but my new commit https://github.com/sonertari/SSLproxy/commit/6f023e5990d3a9c125aeae09fd7326cfe7df073b should fix it. Thanks @janusloo for the report.

**Comment by janusloo** [comment]
Thanks @sonertari. Now the warnings are gone with the latest commit.

I will run it for a few days to see how stable it is. 

In the coming weeks I will apply your custom patches for e2guardian and squid for a test run with sslproxy.

Thank you once again for your support.
