### ISSUE TITLE
fully transparent proxy

### ISSUE THREAD

**Issue by Byeonghong-Son** [sonertari/SSLproxy#64]
Hello

I want to mirror only decoded (HTTP) packets that act as a fully transparent proxy for sslproxy.

client --- router(gateway) --- sslproxy box --- server

Therefore, sslproxy requires a fully transparent proxy configuration that does not act as a separate private or public ip and gateway.

Please give me an example of how to set it up if the related configuration is possible and thank you.

**Comment by sonertari** [comment]
What I understand from your description is that you are looking for a proxy that decrypts HTTPS traffic and pass it to a plain HTTP server. In other words, an HTTPS to HTTP reverse proxy as described here: https://www.jscape.com/blog/https-to-http-reverse-proxy.
If so, SSLproxy is not designed for that purpose.

**Comment by Byeonghong-Son** [comment]
Hello

My explanation was insufficient.

To explain it again

client(HTTS)-----router(gateway)-----sslproxy box(inline mode)---(HTTS)Server
                                                                  |
                                                                  | Mirror Port(HTTP Plain Packet)
                                                                  |
                                                            Packet Caputer Box


I tried to configure an online mode that works completely transparent without setting up public or private ip using nft, iptables, tproxy, etc., but failed.

A fully transparent inline configuration is required with SSL proxy.

Please give me an example of how to set it up if the related configuration is possible and thank you.
